config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  root 'users#new'
  resources :favorites, only:[:create, :destroy, :index]
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only:[:new, :create, :show, :update, :edit]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :content, presence: true
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  mount_uploader :user_image, UserImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name} PicChumイイね!"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name} PicChumイイねを解除しました..."
  end

  def index
    @favorites = current_user.favorite_pictures.order(created_at: :desc)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]

  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all.order(created_at: :desc)
  end

  # GET /pictures/1 or /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  # GET /pictures/1/edit
  def edit
    unless @picture.user == current_user
      redirect_to new_picture_path, notice: "このPicChumは編集できません"
    end
  end

  # POST /pictures or /pictures.json
  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        # PostingMailer.posting_mail(@picture, @picture.user.name, @picture.user.email).deliver
        redirect_to pictures_path, notice: "PicChum投稿完了"
      else
        render :new
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.user != current_user
        redirect_to new_picture_path
      else
        if @picture.update(picture_params)
          format.html { redirect_to picture_url(@picture), notice: "PicChumを更新しました！" }
          format.json { render :show, status: :ok, location: @picture }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    if @picture.user != current_user
      redirect_to new_picture_path, notice: "このPicChumは削除できません"
    else
      @picture.destroy
      respond_to do |format|
      format.html { redirect_to pictures_url, notice: "PicChumを削除しました" }
      format.json { head :no_content }
      end
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  private
  
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:photo, :content, :photo_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインできません。もう一度お試しください。'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました。'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render :new
    else
      if @user.save
        redirect_to user_path(@user.id), notice: "ユーザー登録完了!"
      else
        render :new
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "ユーザー情報を変更しました"
    else
      render :edit
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_image, :user_image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
    picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'favorite_index.jpg'%>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>PicChum</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
          <h1>お気に入り一覧</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <% @favorites.each do |picture| %>
      <!-- Post preview-->
        <div class="post-preview">
        <tr>
          <td><h2 class="post-title"><%= image_tag picture.photo.url, width: '20%', height: '20%' %></h2></td>
          <td><h3 class="post-subtitle"><%= picture.content %></h3></td>
          <td><h3 class="post-meta"><%= picture.user.name %></h3></td>
          <td><p class="post-meta"><%= time_ago_in_words(picture.created_at) %></p></td>
        </tr>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
      <% end %>
      <%= link_to '投稿PicChum一覧', pictures_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>PicChum</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
  </head>

  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
          <a class="navbar-brand" href="https://diveintocode.jp/?utm_medium=cpc&utm_source=google&utm_campaign=brand&gclid=CjwKCAjwtcCVBhA0EiwAT1fY77uSEd-wVg7_neXcUq4QSRgr6hZp5cnHzTdmKagjbpVX_cu0Wh_iwRoCQDYQAvD_BwE">DIVE INTO CODE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
              <% if logged_in? %>
                <li class="nav-item"><%= link_to "Picture Index", pictures_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                <li class="nav-item"><%= link_to "New PicChum", new_picture_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                <li class="nav-item"><%= link_to "User Profile", user_path(current_user.id), class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                <li class="nav-item"><%= link_to "Logout", session_path(current_user.id), method: :delete, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
              <% else %>
                <li class="nav-item"><%= link_to "Sign up", new_user_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                <li class="nav-item"><%= link_to "Login", new_session_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
              <% end %>
            </ul>
          </div>
              </ul>
          </div>
      </div>
    </nav>
    <%= yield %>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <!-- Footer-->
    <footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://twitter.com/seshiruff4214">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://qiita.com/seshiruff4214">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/shota4214">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic">Copyright &copy; shota suzuki 2022</div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit ) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :画像 %>
    <%= image_tag(picture.photo.url) if picture.photo && picture.photo.url %>
    <%= form.file_field :photo %>
    <%= form.hidden_field :photo_cache %>
  </div>

  <div class="field">
    <%= form.label :内容 %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'confirm.jpg' %>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="page-heading">
            <h1>PicChum投稿確認</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
          </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h3>PicChumに投稿する内容は下記で良いですか？</h3>
        <%= form_with(model: @picture, local: true) do |form| %>
          <%= form.hidden_field :photo %>
          <%= form.hidden_field :content %>
          <p>写真</p>
          <%= image_tag(@picture.photo.url) if @picture.photo && @picture.photo.url %>
          <%= form.hidden_field :photo_cache %>
          <p>内容</p>
          <%= @picture.content %><br>
          <%= form.submit  "push" %>
        <% end %>
        <%= form_with(model: @picture, local: true, url: new_picture_path, method: "get") do |form| %>
          <%= form.hidden_field :photo_cache %>
          <%= form.hidden_field :content %>
          <%= form.submit "back", name: "back" %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/pictures/edit.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'picture_edit.jpg' %>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>PicChum</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
          <h2>投稿内容変更</h2>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>投稿したPicChumを変更できます。<br>変更を投稿する場合は下記更新ボタンを押してください。</p>
        <div class="my-5">
          <%= render 'form', picture: @picture %>
          <%= link_to '詳細', @picture, class: "btn btn-outline-info" %> |
          <%= link_to 'PicChum投稿一覧', pictures_path, class: "btn btn-outline-primary" %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/pictures/index.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'picture_index.jpg'%>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>PicChum一覧</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
          <h1></h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <%= link_to "New PicChum", new_picture_path, class: "btn btn-primary" %>新規PicChum投稿<br>
      <br>
      <% @pictures.each do |picture| %>
      <!-- Post preview-->
        <div class="post-preview">
        <tr>
          <td><h2 class="post-title"><%= image_tag picture.photo.url, width: '20%', height: '20%' %></h2></td>
          <td><h3 class="post-subtitle"><%= picture.content %></h3></td>
          <td><h3 class="post-meta"><%= picture.user.name %></h3></td>
          <td><p class="post-meta"><%= time_ago_in_words(picture.created_at) %></p></td>
          <% if picture.user == current_user %>
            <td><%= link_to '詳細', picture, class: "btn btn-outline-info" %></td>
            <td><%= link_to '編集', edit_picture_path(picture), class: "btn btn-outline-warning" %></td>
            <td><%= link_to '削除', picture, method: :delete, data: { confirm: '本当に削除してもですか?' }, class: "btn btn-outline-danger" %></td>
          <% else %>
            <td><%= link_to '詳細', picture, class: "btn btn-outline-info" %></td>
          <% end %>
        </tr>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'picture_new.jpg' %>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>PicChum投稿</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>新規PicChumを投稿します。<br>写真の添付と投稿内容を入力してください。</p>
        <div class="my-5">
          <%= render 'form', picture: @picture %>
          <%= link_to 'PicChum投稿一覧', pictures_path, class: "btn btn-outline-primary" %>
          </div>
        </div>
    </div>
  </div>
</main>

app/views/pictures/show.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'picture_show.jpg' %>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>PicChum詳細</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>投稿したPicChumを確認できます。<br>投稿内容を変更する場合は下記ボタンより変更してください。</p>
        <div class="my-5">
          <p id="notice"><%= notice %></p>
          <p>
            <strong>写真:</strong>
            <%= image_tag @picture.photo.url, width: '20%', height: '20%' %>
          </p>
          <p>
            <strong>内容:</strong>
            <%= @picture.content %>
          </p>
          <% unless @picture.user_id == current_user.id %>
            <% if @favorite.present? %>
              <%= link_to '解除...', favorite_path(id: @favorite.id), method: :delete, class: "btn btn-outline-danger" %>
            <% else %>
              <%= link_to 'PicChumイイね!', favorites_path(picture_id: @picture.id), method: :post, class: "btn btn-outline-success" %>
            <% end %>
          <% end %>
          <% if @picture.user == current_user %>
            <%= link_to '投稿内容変更', edit_picture_path(@picture), class: "btn btn-outline-warning" %> |
            <%= link_to 'PicChum投稿一覧', pictures_path, class: "btn btn-outline-primary" %>
          <% else %>
            <%= link_to 'PicChum投稿一覧', pictures_path, class: "btn btn-outline-primary" %>
          <% end %>
          </div>
        </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'user_edit.jpg' %>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>PicChum</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
          <h2>ユーザー登録内容変更</h2>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>ユーザーの登録内容が変更できます。<br>内容を確認し更新ボタンを押してください。</p>
        <div class="my-5">
          <%= form_with(model: @user, local: true) do |form| %>
            <% if @user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
                <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <%= form.label :user_image %>
              <%= image_tag(@user.user_image.url) if @user.user_image && @user.user_image.url %>
              <%= form.file_field :user_image %>
              <%= form.hidden_field :user_image_cache %>
            </div><br>
            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name %>
            </div><br>
            <div class="field">
              <%= form.label :email %>
              <%= form.email_field :email %>
            </div><br>
            <div class="field">
              <%= form.label :password %>
              <%= form.password_field :password %>
            </div><br>
            <div class="field">
              <%= form.label :password_confirmation %>
              <%= form.password_field :password_confirmation %>
            </div><br>
            <div class="actions">
              <%= form.submit %>
            </div>
            <% end %>
            <%= link_to 'ユーザーページ', @user, class: "btn btn-outline-info" %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'user_show.jpg' %>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>PicChum</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
          <h1>ユーザー登録</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
      <p>PicChumの利用にはユーザーの登録が必要です。<br>ユーザー情報を入力してください。パスワードは６文字以上で入力してください。</p>
        <div class="my-5">
          <%= form_with(model: @user, local: true ) do |form| %>
            <% if @user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
                <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <%= form.label :ユーザー画像 %>
              <%= image_tag(@user.user_image.url) if @user.user_image && @user.user_image.url %>
              <%= form.file_field :user_image %>

            </div><br>
            <div class="field">
              <%= form.label :ユーザー名 %>
              <%= form.text_field :name %>
            </div><br>
            <div class="field">
              <%= form.label :メールアドレス %>
              <%= form.email_field :email %>
            </div><br>
            <div class="field">
              <%= form.label :パスワード %>
              <%= form.password_field :password %>
            </div><br>
            <div class="field">
              <%= form.label :パスワード再入力 %>
              <%= form.password_field :password_confirmation %>
            </div><br>
            <div class="actions">
              <%= form.submit %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<!-- Page Header-->
<header class="masthead" style="background-image: url(<%= asset_path 'user_show.jpg' %>)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>PicChum</h1>
          <span class="subheading">〜Picture（写真）を通してChum（仲良し）になれますに〜</span><br>
          <h1>ユーザーページ</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>ユーザー情報が確認できます。<br>登録情報の変更は下記のボタンをクリック</p>
        <div class="my-5">
          <h1><%= @user.name %> のページ</h1>
          <br>
          <% if @user.user_image? %>
            <%= image_tag @user.user_image.url %>
          <% else %>
            <%= image_tag (asset_path'no_image.png') %>
          <% end %>
          <h3>ユーザー名: <%= @user.name %></h3>
          <p>メールアドレス: <%= @user.email %></p>
        </div>
        <% if @user == current_user %>
            <%= link_to 'ユーザー情報変更', edit_user_path(@user), class: "btn btn-outline-warning" %> |
            <%= link_to 'PicChum投稿一覧', pictures_path, class: "btn btn-outline-primary" %> |
            <%= link_to 'お気に入りPicChum一覧', favorites_path, class: "btn btn-outline-primary" %>
          <% else %>
            <%= link_to 'PicChum index', pictures_path, class: "btn btn-info" %>
          <% end %>
      </div>
    </div>
  </div>
</main>